[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

# [INPUT]
#     Name          random
#     Samples      -1
#     Interval_Sec  1
#     Interval_NSec 0

# [INPUT]
#     Name  dummy
#     Tag   test-input
#     Dummy {"stream":"stderr", "meta": {"cluster_name": "lr-dev-eu-gb-cluster"}, "logtag":"F","severity": 5,"message":{"level":"info","ts":"2023-09-05T11:17:39.227029183Z","logger":"logger-agent-plugin","caller":"internal/logger-agent-plugin-impl.go:199","msg":"PluginFlush called...","tag":"kube.dummy"},"kubernetes":{"pod_name":"logger-agent-vt7hg","namespace_name":"logger-agent","pod_id":"2ba0911a-bf8f-4533-904b-6d119778d160","labels":{"app":"logger-agent","controller-revision-hash":"c7589956f","name":"logger-agent","pod-template-generation":"4","version":"8f1475a8e736ad04ddac39f67a2e7738c1b79f27"},"annotations":{"cni.projectcalico.org/containerID":"ce35ce19999b9cd595f754405adc260741c273e41ad6d0f34a9da80c455c5c92","cni.projectcalico.org/podIP":"172.17.63.176/32","cni.projectcalico.org/podIPs":"172.17.63.176/32","kubectl.kubernetes.io/restartedAt":"2023-08-29T10:45:41+05:30"},"host":"10.242.0.5","container_name":"fluent-bit","docker_id":"6f50825bd4de4cd873e60ed56b5902b352746e1d27c204def32783acf1f4ce5f","container_hash":"us.icr.io/logs-routing/logger-agent-plugin@sha256:2f157a627de28b1025e438e7f300cfa45a27f98caadee52b46f093cb145bfb01","container_image":"us.icr.io/logs-routing/logger-agent-plugin:8f1475a8e736ad04ddac39f67a2e7738c1b79f27"},"IKSlogs":"ikslogs"}

[INPUT]
    Name           tail
    Path           /Users/mila/dev/oss/contrib/fluent-bit/plugins/out_ibm_logs/k8s*.log
    # Path_key       file
    Read_from_head true

[FILTER]
    Name modify
    Match *
    Add file /var/log/containers/mila-test-message-667b49989c-dxk2f_mila-test_mila-test-message-01-359325983bcb856b7bc13c52db0375638ed030bf26e9c5a8421da2ae323d0d00.log

[OUTPUT]
    Name            ibm_logs
    Alias           pupin
    Match           *
    Log_Level       debug

    application_name test-app-name
    subsystem_name   test-subsystem-name

    ibm_logs_host   9a63bad2-b86f-40c8-840b-a9357a20719c.ingress.eu-gb.logs.test.cloud.ibm.com
    ibm_logs_port   443

    ibm_iam_authentication_mode apikey
    ibm_iam_env                 staging
    # ibm_iam_trusted_profile_id  Profile-259b709e-9038-42e5-a702-12a68eaf8eb8
    # cr_token_mount_path         /Users/mila/dev/oss/contrib/fluent-bit/conf/vault-token

    workers 4

    #net.connect_timeout 5s
    #tls on
    #tls.debug 4

# [OUTPUT]
#     Name stdout
#     Match *