[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name           tail
    Path           /Users/mila/dev/oss/contrib/fluent-bit/plugins/out_ibm_logs/k8s*.log
    # Path_key       file
    Read_from_head true

[FILTER]
    Name modify
    Match *
    Add file /var/log/containers/mila-test-message-667b49989c-dxk2f_mila-test_mila-test-message-01-359325983bcb856b7bc13c52db0375638ed030bf26e9c5a8421da2ae323d0d00.log

[OUTPUT]
    Name            ibm_logs
    Alias           pupin
    Match           *
    Log_Level       debug

    application_name test-app-name
    subsystem_name   test-subsystem-name

    ibm_logs_host   localhost
    ibm_logs_port   443

    ibm_iam_authentication_mode apikey
    ibm_iam_env                 staging

    workers 4
