[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

# [INPUT]
#     Name          random
#     Samples      -1
#     Interval_Sec  1
#     Interval_NSec 0

[INPUT]
    Name  dummy
    Tag   test-input
    Dummy {"stream":"stderr", "meta": {"cluster_name": "lr-dev-eu-gb-cluster"}, "logtag":"F","severity": 5,"message":{"level":"info","ts":"2023-09-05T11:17:39.227029183Z","logger":"logger-agent-plugin","caller":"internal/logger-agent-plugin-impl.go:199","msg":"PluginFlush called...","tag":"kube.dummy"},"kubernetes":{"pod_name":"logger-agent-vt7hg","namespace_name":"logger-agent","pod_id":"2ba0911a-bf8f-4533-904b-6d119778d160","labels":{"app":"logger-agent","controller-revision-hash":"c7589956f","name":"logger-agent","pod-template-generation":"4","version":"8f1475a8e736ad04ddac39f67a2e7738c1b79f27"},"annotations":{"cni.projectcalico.org/containerID":"ce35ce19999b9cd595f754405adc260741c273e41ad6d0f34a9da80c455c5c92","cni.projectcalico.org/podIP":"172.17.63.176/32","cni.projectcalico.org/podIPs":"172.17.63.176/32","kubectl.kubernetes.io/restartedAt":"2023-08-29T10:45:41+05:30"},"host":"10.242.0.5","container_name":"fluent-bit","docker_id":"6f50825bd4de4cd873e60ed56b5902b352746e1d27c204def32783acf1f4ce5f","container_hash":"us.icr.io/logs-routing/logger-agent-plugin@sha256:2f157a627de28b1025e438e7f300cfa45a27f98caadee52b46f093cb145bfb01","container_image":"us.icr.io/logs-routing/logger-agent-plugin:8f1475a8e736ad04ddac39f67a2e7738c1b79f27"},"IKSlogs":"ikslogs"}


[OUTPUT]
    Name            ibm_logs
    Alias           pupin
    Match           *
    Log_Level       debug

    #IBM Cloud Logs
    ibm_logs_host   668e4b39-6c50-4102-b46a-d1ee8fbff596.ingress.eu-de.logs.cloud.ibm.com
    ibm_logs_port   443

    #IBM IAM auth
    ibm_iam_authentication_mode apikey
    ibm_iam_env                 staging

# [OUTPUT]
#     Name stdout
#     Match *